[dev]
app-dev ansible_host=192.168.56.10

[prod]
app-prod1 ansible_host=192.168.56.11

[app:children]
dev
prod

[ci]
jenkins ansible_host=192.168.56.13

[sonar]
sonarqube ansible_host=192.168.56.14

[all:vars]
ansible_user=admin
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_private_key_file=~/.ssh/id-rda-infra.key
ansible_ssh_common_args='-o StrictHostKeyChecking=accept-new'
